# Generated by Django 3.1.1 on 2020-11-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
                ('software_version', models.CharField(max_length=50)),
                ('last_update', models.DateTimeField()),
            ],
        ),
    ]
