# Generated by Django 3.1.1 on 2021-01-13 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_sessions_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlist',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
